[project]
name = "devopx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.121.3",
    "fastapi-cli>=0.0.16",
    "loguru>=0.7.3",
    "uvicorn>=0.38.0",
]
