name: 01 - Building Blocks

on:
    workflow_dispatch:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]
# type: [created, edited, synchronize]

jobs:
    sample-ok:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v6
        -   name: Run script
            run: |
                echo "Bash CICD my project"
    with-exit-code:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v6
        -   name: Failed - Run script
            run: |
                echo "Want to say goodbye"
                echo "Bye"
                exit 0
