name: 01 - Building Blocks

on:
  workflow_dispatch:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  sample-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Run script
      run: |
        echo "Bash CICD my project"
        exit 0
  sample-gone:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Failed - Run script
      run: |
        echo "Want to say goodbye"
        echo "Bye"
        exit 1
