---
name: 05 1 - Filter Activity Types
on:
    workflow_dispatch:
    push:
        branches: [main, develop]
    pull_request:
        types: [opened, synchronize]
        branches: [main]

jobs:
    sample-ok:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Run script
              run: |
                  echo "Running whenever  a PR is opened or synchronized AND base branch is main"
                  echo "Event: ${{ github.event_name }}"
                  echo "GRACE: God's Riches At Christ's Expense"
                    if [[ ${{ github.event_name }} == "push" ]]; then
                        echo "Pushed to main"
                    fi
